version: '3.7'
services:
  maria:
    image: mariadb:latest
    ports: 
    - "3306:3306"
    environment:       
      MYSQL_USER: chapolin
      MYSQL_PASSWORD: colorado
      MYSQL_DATABASE: chaves
      MYSQL_ROOT_PASSWORD: pastilhaencolheradora
      TZ: America/Sao_Paulo        
  redis:
    image: redis:latest      
  mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'        
  dev:    
    image: tiagoheineck/laravel:php7.4-cli-xdebug        
    ports:
    - "8000:8000"
    volumes:    
    - '.:/app'
    working_dir: /app
    links:
    - maria
    - redis
    - mailhog
    command: /bin/sh -c "composer install && php artisan migrate:fresh --seed && php artisan serve --host 0.0.0.0"